### ISSUE TITLE
Example for using the Web Services directly

### ISSUE THREAD

**Issue by genericpenguin** [zentourist/viewpoint-spws#1]
Sorry, it's not an issue; more of a suggestion.

It might be useful to have some examples of using the Web Services classes directly (unless you don't want people to).  I needed to get a list with a different view and it helped me. Just something like:

site = 'http://sharepoint_server/site/default.aspx'
spcon = Viewpoint::SPWS::Connection.new(site)
spcon.set_auth(username,password)
lists = Viewpoint::SPWS::Websvc::Lists.new(spcon)
servers = lists.get_list_items('List Name', :view_name => 'ffea6723-8ac5-4166-9d5a-c2e3b4ca8514')

BTW, thanks for writing it. It's really nice to have something simple to use to access Sharepoint.

**Comment by zentourist** [comment]
I hope to eventually build most of the functionality into the front-end models. As for the back-end web services I try and link to Microsoft's documentation for all of the relevant methods so hopefully people can figure out their own specific use-cases. There are also the models that can be looked at if you're looking for example usage of the back-end web services. I know that more documentation is always good but I just don't have the resources to go all out... sorry.

Cheers,

Dan

**Comment by genericpenguin** [comment]
No probs; that's understandable.  I appreciate the response and look forward to additional features in the future. Once again, thanks for writing it. It has been very helpful.
